# Uncomment the next line to define a global platform for your project
platform :ios, '18.5'

target 'AuthenticationExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AuthenticationExample
  ## Firebase 🔥 Pods
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'

  ## Pod for Sign in with Google
  pod 'GoogleSignIn'
  
  #<gen>ios_podfile
  pod 'mailslurp', :git => 'https://github.com/mailslurp/mailslurp-client-swift.git'
  #</gen>
  
  ## Pod for Sign in with Facebook
  pod 'FBSDKLoginKit'

  target 'AuthenticationExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AuthenticationExampleUITests' do
    # Pods for testing
  end

end
