# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "mailslurp_client", "~> 11.5"

gem "capybara", "~> 3.35"

gem "selenium-webdriver", "~> 3.142"

gem "cucumber", "~> 5.3"

gem "typhoeus", "~> 1.4"

gem "rspec", "~> 3.10"
